/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // --- Dark theme (Material-3-style tokens) — "Ledger & Brass" ---
        // A deep ink surface with a warm brass/gold accent (the Kaizen "seal")
        // and a cool lagoon teal as the secondary voice.
        'on-secondary-fixed-variant': '#3F4750',
        'surface-container-low': '#0D1B2E',
        secondary: '#B9C9DD',
        'error-container': '#93000A',
        'surface-dim': '#070E19',
        'on-secondary-fixed': '#16222C',
        'on-primary': '#FFF8EC',
        'on-secondary-container': '#DCE6F5',
        'on-secondary': '#142236',
        'surface-container-lowest': '#050B14',
        'inverse-surface': '#EEF4FB',
        'on-primary-fixed-variant': '#6B4A1D',
        'primary-fixed': '#F3E4C7',
        'on-tertiary-container': '#BFF3E2',
        'on-background': '#EEF4FB',
        'tertiary-fixed': '#CFF5E7',
        'on-tertiary-fixed-variant': '#0F5645',
        'on-error-container': '#FFDAD6',
        'primary-fixed-dim': '#C9A876',
        'primary-container': '#8C5E1D',
        'surface-container-high': '#182C45',
        'secondary-container': '#1C334E',
        background: '#0A1420',
        'tertiary-container': '#0F5645',
        error: '#FFB4AB',
        'on-primary-fixed': '#3B2A10',
        'on-surface': '#EEF4FB',
        'tertiary-fixed-dim': '#8FE4C9',
        'on-tertiary': '#06231C',
        'on-tertiary-fixed': '#06231C',
        'on-primary-container': '#FFF1DC',
        'on-surface-variant': '#93A7C1',
        tertiary: '#4FD3B0',
        'surface-container': '#122238',
        'surface-tint': '#8A6A3E',
        'secondary-fixed-dim': '#B7C2CF',
        'outline-variant': '#23374F',
        'secondary-fixed': '#DDE3EB',
        'surface-variant': '#24405F',
        outline: '#5E7690',
        'surface-bright': '#17293F',
        'inverse-primary': '#6B4A1D',
        primary: '#D9A75B',
        surface: '#101F35',
        'surface-container-highest': '#1F3450',
        'inverse-on-surface': '#101F35',
        'on-error': '#690005',

        // --- Kaizen brand tokens (from flyer references) ---
        navy: '#14314F',
        'navy-deep': '#050D18',
        blue: '#3E7BFF',
        teal: '#2FCDA8',
        'teal-soft': '#0F2C26',
        'teal-deep': '#0C6F5C',
        cream: '#FAF7F0',
        gold: '#D9A75B',
        'gold-deep': '#8C5E1D',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        'section-gap-mobile': '64px',
        'section-gap-desktop': '120px',
        'container-max-width': '1200px',
        'grid-gutter': '24px',
        base: '8px',
        'card-padding': '32px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg': ['"Space Grotesk"', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      boxShadow: {
        ambient: '0 10px 30px rgba(2, 7, 15, 0.35)',
        'ambient-hover': '0 20px 48px rgba(2, 7, 15, 0.5)',
        card: '0 8px 24px rgba(2, 7, 15, 0.3)',
        'card-hover': '0 20px 45px rgba(2, 7, 15, 0.45)',
        soft: '0 4px 14px rgba(2, 7, 15, 0.3)',
        glow: '0 0 0 1px rgba(217,167,91,0.25), 0 12px 30px -8px rgba(217,167,91,0.35)',
        'glow-hover': '0 0 0 1px rgba(217,167,91,0.4), 0 20px 45px -8px rgba(217,167,91,0.5)',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-18px) translateX(8px)' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'spin-slower': {
          from: { transform: 'rotate(360deg)' },
          to: { transform: 'rotate(0deg)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'fade-in': {
          from: { opacity: 0 },
          to: { opacity: 1 },
        },
        'grid-pan': {
          from: { backgroundPosition: '0 0' },
          to: { backgroundPosition: '64px 64px' },
        },
      },
      animation: {
        float: 'float 7s ease-in-out infinite',
        'float-delay': 'float 8.5s ease-in-out 1.2s infinite',
        'spin-slow': 'spin-slow 16s linear infinite',
        'spin-slower': 'spin-slower 22s linear infinite',
        shimmer: 'shimmer 2.4s linear infinite',
        'fade-in': 'fade-in 0.6s ease-out both',
        'grid-pan': 'grid-pan 12s linear infinite',
      },
    },
  },
  plugins: [],
};
